### ISSUE TITLE
How to set option/setting for later use?

### ISSUE THREAD

**Issue by 1c7** [punkave/sanitize-html#255]
## 1. For now, the only way to set option, is when using it
```javascript
var sanitizeHtml = require('sanitize-html');

var dirty = 'some really tacky HTML';
clean = sanitizeHtml(dirty, {  // must pass in dirty HTML
  allowedTags: sanitizeHtml.defaults.allowedTags.concat([ 'img' ])
});
```

#### Maybe something like this:
```javascript
var sanitizeHtml = require('sanitize-html');

// set option
sanitizeHtml.options({
  allowedTags: sanitizeHtml.defaults.allowedTags.concat([ 'img' ])
})
```
and later just

```javascript
   sanitizeHtml(dirty)
```

## In short
from this
```
sanitize(HTML, option);
```

to this
```
sanitize.option({...});
sanitize(HTML)
```

### Why?  
So I can put sanitizeHTML into one file like `custom-sanitize-html.js` and use it in multiple place later
I don't have to copy setting every time

**I already read README, and search in Github issue, can't find answer**

Thank you

**Comment by boutell** [comment]
This is really more of a general javascript question. This module gives you a function that can take an options object and some HTML, and sanitize according to those options. You can create a function yourself that does what you want:

```
function mySanitize(html) {
  return sanitize(html, { options the way you want them } );
}
```

Now call mySanitize(html) anywhere you like. You're not finding this in the README or github issues because it's more of a general question about javascript programming and how to write functions that call other functions in useful ways.

**Comment by 1c7** [comment]
@boutell  Thank you!
