### ISSUE TITLE
"Class" is a reserved word in JS

### ISSUE THREAD

**Issue by adregan** [punkave/sanitize-html#32]
I'm a little concerned about using the class keyword as a property as it is a reserved keyword and there will "soon" be JS classes:
```
clean = sanitizeHtml(dirty, {
  transformTags: {
    'ol': function(tagName, attribs) {
        // My own custom magic goes here

        return {
            tagName: 'ul',
            attribs: {
                class: 'foo'
            }
        };
    }
  }
});
```
React.js uses className for this very reason.

**Comment by boutell** [comment]
This is permitted; object property names in literals are IdentifierNames, not Identifiers.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

There's a little potential for confusion perhaps, but the die was cast a while ago and this has been considered 100% OK since ES5, so I don't think it's worth a bc break.
