### ISSUE TITLE
Strings containing double quotes are returned with the quotes encoded

### ISSUE THREAD

**Issue by jacobmoe** [punkave/sanitize-html#41]
The latest version is encoding quotes. 

    var html = 'hello "world"'
    sanitizeHtml(html, {
      allowedTags: allowedTags,
      transformTags: {
        a: function(tag, attrs) {
          return {
            tagName: 'a',
            attrs: {
              href: attrs.href,
              target: '_blank'
            }
          }
        }
      }
    })

will return

    hello &quot;world&quot;

This wasn't happening in 1.4.3

**Comment by boutell** [comment]
This doesn't impact the output in the browser. But we could skip the
encoding of quotes when we know we're dealing with text rather than
attributes. I'd accept a pull request for that.



On Wed, Feb 11, 2015 at 1:11 PM, jacobmoe <notifications@github.com> wrote:

> The latest version is encoding quotes.
>
> var html = 'hello "world"'
> sanitizeHtml(html, {
>   allowedTags: allowedTags,
>   transformTags: {
>     a: function(tag, attrs) {
>       return {
>         tagName: 'a',
>         attrs: {
>           href: attrs.href,
>           target: '_blank'
>         }
>       }
>     }
>   }
> })
>
> will return
>
> hello &quot;world&quot;
>
> This wasn't happening in 1.4.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/41>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
