### ISSUE TITLE
Please add tag/releases for bower

### ISSUE THREAD

**Issue by homerjam** [punkave/sanitize-html#46]
Hi,

Thanks for the great work.

I'm using bower and whilst its great that this package is on there, it'd be even better if it were tagged so as not to always opt for the master.

Thanks

**Comment by boutell** [comment]
I see that you closed it, but I don't recall ever doing anything to put this on bower?

I'm not sure it would be a great fit with bower because it depends on a fairly long chain of npm modules. On a server that's completely fine, in the browser maybe not.

Also, you can't really trust a browser to sanitize things... that should happen in a trusted space.

**Comment by homerjam** [comment]
Yeah, I jumped the gun. I didn't really check out the module properly - I thought because it was on bower it must be suitable for client side use. As soon as I realised I closed the issue. Sorry to waste your time!
