### ISSUE TITLE
& in content is escaped to &amp;

### ISSUE THREAD

**Issue by brunops** [punkave/sanitize-html#69]
Not sure if this happens as designed, but it's not wanted for me.

``` js
var sanitize = require('sanitize-html');

console.log(sanitize("Hello & bye", { allowedTags: [] })); // Hello &amp; bye
```

There's no HTML tag in the content, but the module is still encoding the HTML entities, it happens for `<` and `>` as well, not sure if for other entities.

thanks

**Comment by boutell** [comment]
Prior to HTML5 this was just plain wrong. HTML5 officially tolerates it,
but getting it right is much harder than just escaping reasonably; it
requires lookahead to determine that the & is not followed by something
that "looks like a character reference."

It doesn't matter if there's an "HTML tag in the content." It's called
sanitize-html because its output is a valid HTML fragment. Not plaintext,
and certainly not an XSS attack vector (:

On Wed, Aug 12, 2015 at 7:01 PM, Bruno Sanches <notifications@github.com>
wrote:

> Not sure if this happens as designed, but it's not wanted for me.
>
> var sanitize = require('sanitize-html');
> console.log(sanitize("Hello & bye", { allowedTags: [] })); // Hello &amp; bye
>
> There's no HTML tag in the content, but the module is still encoding the
> HTML entities, it happens for < and > as well, not sure if for other
> entities.
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/69>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by slidenerd** [comment]
I have the same issue, glad I found this, is there any way I can tell sanitize-html hey look at that ampersand sign, dont turn that into &amp;

**Comment by boutell** [comment]
This ticket is closed for a reason, see my comment above. Sorry.
