### ISSUE TITLE
Ability to run in the browser?

### ISSUE THREAD

**Issue by cmckni3** [punkave/sanitize-html#74]
I am trying to use `sanitizeHtml` in the browser but it doesn't appear to work. Webpack gives errors that it can't find the package. Sometimes I receive `html2parser` errors.

Can `sanitize-html` run in the browser?

**Comment by boutell** [comment]
I can't think of any reason why it wouldn't work, but it would probably be
very large; someone tried this before and complained that htmlparser2 had a
lot of dependencies that made it huge in the browser or something.

My response was that sanitizing things in the browser is a fundamentally
bad idea because while it might have some legitimate use, it presents a big
moral hazard that you'll actually trust that data when it gets to your
server!

On Mon, Aug 31, 2015 at 4:50 PM, Chris McKnight <notifications@github.com>
wrote:

> I am trying to use sanitizeHtml in the browser but it doesn't appear to
> work. Webpack gives errors that it can't find the package. Sometimes I
> receive html2parser errors.
>
> Can sanitize-html run in the browser?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/74>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Open to chatting about this, but since running in the browser is currently not considered in scope or a good idea, I'm going to close the issue for housekeeping.

**Comment by cmckni3** [comment]
Yeah, I agree that it's a bad idea to sanitize on the client only. My use case for it right now is giving a preview of the sanitized version of the text.

**Comment by boutell** [comment]
That does sound useful. I suggest using an AJAX call to get it though.

On Mon, Aug 31, 2015 at 7:10 PM, Chris McKnight <notifications@github.com>
wrote:

> Yeah, I agree that it's a bad idea to sanitize on the client only. My use
> case for it right now is giving a preview of the sanitized version of the
> text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/74#issuecomment-136524429>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
