### ISSUE TITLE
exclusiveFilter frame.text doesn't take into consideration inner tags

### ISSUE THREAD

**Issue by ohjimijimijimi** [punkave/sanitize-html#76]
Let's consider the filter example in the documentation but with a different use case
```
sanitizeHtml(
    '<a><img src="http://dummyimage.com/600x300" /></a>',
    {
        exclusiveFilter: function(frame) {
            return frame.tag === 'a' && !frame.text.trim();
        }
    }
);
```
What I expect is:
```
"<a><img src="http://dummyimage.com/600x300" /></a>"
``` 
instead the output is 
```
"" # empty string
```

The frame.text contains just the text value of the tag and it doesn't consider nested tag.

Am I missing something? Is there a way to achieve this behavior?

**Comment by boutell** [comment]
It's called "text" because that's all you get. The text of that tag.

I understand what you want to do but it requires representing the entire
document as a tree. Once I do that, you'll want to know where the tree
traversal features are. And once I've done that, I'll have reinvented
cheerio, which I suspect is better suited to your use case.




On Mon, Sep 28, 2015 at 5:40 PM, Sirio Marchi <notifications@github.com>
wrote:

> Let's consider the filter example in the documentation but with a
> different use case
>
> sanitizeHtml(
>     '<a><img src="http://dummyimage.com/600x300" /></a>',
>     {
>         exclusiveFilter: function(frame) {
>             return frame.tag === 'a' && !frame.text.trim();
>         }
>     }
> );
>
> What I expect is "<a><img src="http://dummyimage.com/600x300" /></a>"
> instead the output is "". The frame.text contains just the text value of
> the tag and it doesn't consider nested tag.
> Am I missing something? Is there a way to achieve this behavior?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/76>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by ohjimijimijimi** [comment]
yes, I know. I was wondering if maybe in the parser used was already doing that. You're correct about cheerio, indeed I used that. Thanks for clarifying the concept.
